# <p style="background-color:green;font-family:newtimeroman;font-size:200%;color:white;text-align:center;border-radius:20px 20px;"><b>Numpy-Pandas Interview Questions</b></p>
![](https://www.techproeducation.com/logo/headerlogo.svg)

<b>Yeniliklerden ilk siz haberdar olmak istiyorsanız lütfen bizi takip etmeyi unutmayın </b>[YouTube](https://www.youtube.com/c/techproeducation) | [Instagram](https://www.instagram.com/techproeducation) | [Facebook](https://www.facebook.com/techproeducation) | [Telegram](https://t.me/joinchat/HH2qRvA-ulh4OWbb) | [Whatsapp](https://api.whatsapp.com/send/?phone=%2B15853042959&text&type=phone_number&app_absent=0) | [LinkedIn](https://www.linkedin.com/company/techproeducation/mycompany/) |

https://www.stratascratch.com/

## Numpy soruları

### 1. Numpy nedir ne amaçla kullanılır?

https://numpy.org/doc/stable/user/absolute_beginners.html#

NumPy (Sayısal Python), bilim ve mühendislikte yaygın olarak kullanılan açık kaynaklı bir Python kütüphanesidir. NumPy kütüphanesi, homojen, N boyutlu ndarray gibi çok boyutlu dizi veri yapıları ve bu veri yapıları üzerinde etkili bir şekilde çalışan büyük bir fonksiyon kütüphanesi içerir.

NumPy, aşağıdakiler dahil olmak üzere geniş bir uygulama yelpazesi için kullanılır:

Bilimsel Hesaplama: NumPy, matematiksel, bilimsel ve mühendislik hesaplamaları için olmazsa olmaz bir araçtır. Verimli dizi işlemleri, doğrusal cebir rutinleri, Fourier dönüşümleri ve rastgele sayı üretimi gibi özellikler sunar.

Veri Analizi: NumPy, büyük veri kümelerini işlemede ve analiz etmede oldukça etkilidir. Verileri temizleme, dönüştürme ve şekillendirme gibi görevleri kolaylaştırır.

Makine Öğrenmesi: NumPy dizileri, çoğu makine öğrenmesi algoritması için verimli bir veri yapısı sağlar. Scikit-learn gibi birçok makine öğrenmesi kütüphanesi, NumPy dizilerini temel veri yapısı olarak kullanır.

Görüntü İşleme: NumPy dizileri, görüntüleri temsil etmek ve işlemek için kullanılabilir. OpenCV gibi görüntü işleme kütüphaneleri NumPy'yi temel bir bağımlılık olarak kullanır.

Finansal Modelleme: NumPy, finansal modellemede kullanılan karmaşık matematiksel hesaplamaları gerçekleştirmek için kullanılabilir.

### 2. Numpy ile 1D, 2D ve 3D array nasıl oluşturursunuz?

In [1]:
#1D array (Vektörler)
import numpy as np
# Liste kullanarak 1D dizi oluşturma
dizi_1d = np.array([1, 2, 3, 4, 5])

# Sıfırlardan oluşan 1D dizi oluşturma
sifirlar_1d = np.zeros(5)

# Birlerden oluşan 1D dizi oluşturma
birler_1d = np.ones(5)

# Belirli bir aralıkta değerler içeren 1D dizi oluşturma
aralik_1d = np.arange(1, 10, 2) 

In [2]:
print(dizi_1d)
print(sifirlar_1d)
print(birler_1d)
print(aralik_1d)

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 3 5 7 9]


In [29]:
# 2D array (Matrisler)

# İçiçe liste kullanarak 2D dizi oluşturma
dizi_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Sıfırlardan oluşan 2D dizi oluşturma
sifirlar_2d = np.zeros((3, 4)) # 3 satır, 4 sütun

# Birlerden oluşan 2D dizi oluşturma
birler_2d = np.ones((2, 3)) # 2 satır, 3 sütun

# Rastgele sayılardan oluşan 2D dizi oluşturma
rastgele_2d = np.random.rand(2, 2) # randint

print(dizi_2d)
print(sifirlar_2d)
print(birler_2d)
print(rastgele_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.39347153 0.07214654]
 [0.8831293  0.63704386]]


In [36]:
# 3D array (Tensörler)

# İçiçe listeler kullanarak 3D dizi oluşturma
dizi_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Sıfırlardan oluşan 3D dizi oluşturma
sifirlar_3d = np.zeros((2, 3, 4)) # 2 derinlik, 3 satır, 4 sütun

# Birlerden oluşan 3D dizi oluşturma
birler_3d = np.ones((3, 2, 2)) # 3 derinlik, 2 satır, 2 sütun

print(dizi_3d)
print(sifirlar_3d)
print(birler_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


---

In [3]:
import numpy as np

arr1 = np.arange(0,2)
arr2 = np.arange(6,10).reshape(2,-1)
arr3 = np.array([[0,1],[1,0]])
arr1, arr2, arr3

(array([0, 1]),
 array([[6, 7],
        [8, 9]]),
 array([[0, 1],
        [1, 0]]))

### 3. arr1 ve arr2'yi nasıl toplarsınız?

In [5]:
print(arr1,"*"*9, arr2, sep="\n")

[0 1]
*********
[[6 7]
 [8 9]]


In [8]:
arr1 + arr2

array([[ 6,  8],
       [ 8, 10]])

### 4. arr2 ve arr3 arraylerini horizontal ve vertical olarak nasıl birleştirirsiniz (concat)?

In [6]:
print(arr2,"*"*9, arr3, sep="\n")

[[6 7]
 [8 9]]
*********
[[0 1]
 [1 0]]


In [9]:
np.concatenate((arr2, arr3), axis=1)

array([[6, 7, 0, 1],
       [8, 9, 1, 0]])

In [10]:
np.concatenate((arr2, arr3), axis=0)

array([[6, 7],
       [8, 9],
       [0, 1],
       [1, 0]])

### 5. [4,1,5,7,0] dizesindeki en büyük iki elemanın indexini numpy ile nasıl gösterirsiniz?

In [7]:
np.argsort([4,1,5,7,0])

array([4, 1, 0, 2, 3])

In [11]:
np.argsort([4,1,5,7,0])[-2:] # küçükten büyüğe sıralayarak indexleri gösterir.

array([2, 3])

### 6. Numpy'da np.mean() ve np.average() arasındaki fark nedir?


* np.mean() yöntemi aritmetik ortalamayı hesaplar ve girdi ve sonuçlar için ek seçenekler sunar. Örneğin, hangi veri türlerinin alınması gerektiğini, sonucun nereye yerleştirilmesi gerektiğini vb. belirtme seçeneğine sahiptir. 

* np.average() weights parametresi belirtilirse ağırlıklı ortalamayı hesaplar. Ağırlıklı ortalama durumunda, her veri noktasının nihai ortalamaya eşit şekilde katkıda bulunduğunu düşünmek yerine, bazı veri noktalarının diğerlerinden daha fazla ağırlığa sahip olduğunu (eşit olmayan katkı) düşünür.

In [8]:
#np.mean()
a = np.array([1, 2, 3, 4])
ortalama = np.mean(a)
print(ortalama)

2.5


In [9]:
#np.average()
a = np.array([1, 2, 3, 4])
agirliklar = np.array([4, 3, 2, 1])
agirlikli_ortalama = np.average(a, weights=agirliklar)
print(agirlikli_ortalama)

2.0


### 7. arr[:,0] ve arr[:,[0]] arasında ne fark var?

arr[:,0] tek boyutlu bir vektör döndürürken, arr[:,[0]] iki boyutlu bir matris döndürür.


In [10]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[:,0]) 

[1 4 7]


In [40]:
print(arr[:,[0]]) # 0. indexe bir boyut ekle o şekilde getir.

[[1]
 [4]
 [7]]


### 8. Bir pandas DataFrame'i Numpy array'e nasıl dönüştürürsünüz?

In [41]:
# Bir DataFrame oluşturun
data = {'isim': ['Ali', 'Veli', 'Ayşe'],
        'yaş': [25, 30, 28],
        'şehir': ['Ankara', 'İstanbul', 'İzmir']}
df = pd.DataFrame(data)

# DataFrame'i NumPy dizisine dönüştürün
dizi = df.to_numpy()

print("DataFrame:\n", df)
print("\nNumPy Dizisi:\n", dizi)

DataFrame:
    isim  yaş     şehir
0   Ali   25    Ankara
1  Veli   30  İstanbul
2  Ayşe   28     İzmir

NumPy Dizisi:
 [['Ali' 25 'Ankara']
 ['Veli' 30 'İstanbul']
 ['Ayşe' 28 'İzmir']]


### 9. Verilen bir NumPy arrayin bir dize öğesini büyük harfe, küçük harfe, ilk harfi büyük harfe, başlığı büyük harfe ve swapcase'e dönüştüren bir program yazın.?

In [43]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['Hello world', 'numpy is great', 'Python Programming'])

# Convert to different cases
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
capitalized_array = np.char.capitalize(string_array)
titlecase_array = np.char.title(string_array)
swapcase_array = np.char.swapcase(string_array)

# Print the results
print("Original Array:")
print(string_array)
print("\nUppercase:")
print(uppercase_array)
print("\nLowercase:")
print(lowercase_array)
print("\nCapitalized:")
print(capitalized_array)
print("\nTitle Case:")
print(titlecase_array)
print("\nSwap Case:")
print(swapcase_array)

Original Array:
['Hello world' 'numpy is great' 'Python Programming']

Uppercase:
['HELLO WORLD' 'NUMPY IS GREAT' 'PYTHON PROGRAMMING']

Lowercase:
['hello world' 'numpy is great' 'python programming']

Capitalized:
['Hello world' 'Numpy is great' 'Python programming']

Title Case:
['Hello World' 'Numpy Is Great' 'Python Programming']

Swap Case:
['hELLO WORLD' 'NUMPY IS GREAT' 'pYTHON pROGRAMMING']


---

# <p style="background-color:green;font-family:newtimeroman;font-size:100%;color:white;text-align:center;border-radius:20px 20px;"><b>Faydalı Olması Temennisiyle Teşekkürler</b></p>
![](https://www.techproeducation.com/logo/headerlogo.svg)

<b>Yeniliklerden ilk siz haberdar olmak istiyorsanız lütfen bizi takip etmeyi unutmayın </b>[YouTube](https://www.youtube.com/c/techproeducation) | [Instagram](https://www.instagram.com/techproeducation) | [Facebook](https://www.facebook.com/techproeducation) | [Telegram](https://t.me/joinchat/HH2qRvA-ulh4OWbb) | [Whatsapp](https://api.whatsapp.com/send/?phone=%2B15853042959&text&type=phone_number&app_absent=0) | [LinkedIn](https://www.linkedin.com/company/techproeducation/mycompany/) |