In [2]:
import numpy as np

In [22]:
a = np.array([[1,2,3],
          [4,"ankara",6],
          [7,8,9]])

In [24]:
a.dtype

dtype('<U11')

In [ ]:
# hiç bir zaman korkuya endişeye gerek yok sevgili dostum
# bu programları öğrenmek zor değil ve sen başarırsın, elinin altında yeterli sayıda doküman mevcut. 
# şimdi olmazsa iki hafta sonra öğrenirsin hiç sorun olmayacak canını sıkma inş. 
# inş süper bir data scientist olacaksın sen bak da gör... 


In [18]:
a = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
a[1][1].dtype

dtype('int32')

In [26]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [30]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [34]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [36]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [38]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [67]:
a = np.array([1,2,3],dtype = 'int16')
a

array([1, 2, 3], dtype=int16)

In [49]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [51]:
a.ndim

1

In [53]:
b.ndim

2

In [55]:
a.shape

(3,)

In [57]:
b.shape

(2, 3)

In [69]:
a.dtype

dtype('int16')

In [61]:
b.dtype

dtype('float64')

In [71]:
a.itemsize

2

In [73]:
a.size

3